### PR TITLE
Only support update sts

### PR DESCRIPTION
**Pull request by DanielXLee**
Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36467
@kgcarr I noticed that too update `service` resource will cause the error as following
```console
{"level":"error","ts":1588909382.0103092,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"mongodb-controller","request":"ibm-common-services/ibm-mongodb","error":"could not Update resource: Service \"mongodb\" is invalid: [metadata.resourceVersion: Invalid value: \"\": must be specified for an update, spec.clusterIP: Invalid value: \"\": field is immutable]"
```

Currently, all API attributes are only used for sts, so I think we only need to update sts, and other resources do not need it, which will avoid updating `service`.

### CODE REVIEW

**Comment by renshichuang** [comment]
cc @chenzhiwei @horis233

**Comment by kgcarr** [comment]
This won't protect against the other way where a client updates one of the mongodb resources and the operator sets it back

**Comment by horis233** [comment]
@kgcarr I think that is a function of the operator. Users should update the CR to update the operands. If users want to update the resource directly, they need to uninstall the operator.

**Comment by kgcarr** [comment]
@horis233 right, currently this operator does not enforce that. You can install with operator, go change the configmap and the operator will not go and set it back.

**Comment by DanielXLee** [comment]
This fix only handles user update `OperandConfig` case.

**Comment by kgcarr** [comment]
I tested this PR and it does work to support statefulset changes
/lgtm

**Pull request merged**
